# keywords.py
keywords = [
    "nature", "animals", "shoes", "city", "beach", "food", "business", "travel", "fashion", "technology",
    "portrait", "family", "landscape", "sunset", "sky", "mountains", "ocean", "forest", "flowers", "wedding",
    "children", "computers", "office", "architecture", "sports", "music", "abstract", "autumn", "winter", "summer",
    "spring", "holiday", "Christmas", "pets", "wildlife", "yoga", "gym", "fitness", "party", "birthday",
    "background", "vintage", "modern", "water", "rain", "snow", "desert", "street", "urban", "rural", "night",
    "stars", "moon", "celebration", "cars", "transportation", "aerial", "drone", "macro", "insects", "birds",
    "underwater", "fish", "coral", "space", "galaxy", "universe", "sunrise", "clouds", "hiking", "adventure",
    "camping", "fire", "waterfall", "rainbow", "children playing", "elderly", "couple", "love", "romantic", "cooking",
    "baking", "restaurant", "cafe", "coffee", "tea", "fruits", "vegetables", "meat", "dessert", "chocolate", "wine",
    "cocktails", "books", "reading", "writing", "education", "school", "university", "students", "teachers", "classroom",
    "science", "lab", "research", "health", "medicine", "hospital", "nurse", "doctor", "surgery", "vaccination", "pills",
    "pharmacy", "mental health", "wellness", "spa", "relaxation", "massage", "meditation", "pregnancy", "baby", "newborn",
    "toddler", "teenagers", "adults", "work", "meeting", "conference", "seminar", "presentation", "team", "leadership",
    "innovation", "strategy", "success", "failure", "challenge", "motivation", "inspiration", "finance", "money", "bank",
    "investment", "stocks", "real estate", "home", "interior", "decor", "furniture", "garden", "plants", "cactus",
    "sustainability", "recycling", "renewable energy", "solar", "wind", "electric car", "pollution", "climate change",
    "global warming", "natural disaster", "earthquake", "volcano", "tsunami", "flood", "storm", "tornado", "hurricane",
    "wildfire", "farm", "agriculture", "cows", "sheep", "chickens", "harvest", "crops", "market", "shopping", "retail",
    "fashion show", "models", "makeup", "beauty", "jewelry", "accessories", "shirts", "dresses", "pants", "suits",
    "hats", "sunglasses", "shadows", "reflection", "mirror", "glass", "window", "door", "stairs", "bridge", "river",
    "lake", "pond", "swimming", "diving", "surfing", "skiing", "snowboarding", "cycling", "motorcycle", "train",
    "airplane", "airport", "station", "harbor", "ship", "boat", "yacht", "cruise", "island", "tropical", "paradise",
    "vacation", "resort", "hotel", "backpacking", "map", "compass", "camera", "photography", "art", "painting", "drawing",
    "museum", "gallery", "sculpture", "dance", "ballet", "theater", "cinema", "film", "television", "radio", "podcast",
    "headphones", "guitar", "piano", "drums", "singing", "concert", "festival", "performance", "circus", "magic",
    "illusion", "comedy", "tragedy", "drama", "horror", "thriller", "mystery", "fantasy", "sci-fi", "romance", "history",
    "war", "peace", "politics", "election", "vote", "protest", "rights", "freedom", "justice", "law", "court", "police",
    "firefighter", "military", "soldiers", "weapon", "news", "newspaper", "magazine", "internet", "social media", "apps",
    "smartphone", "tablet", "laptop", "desktop", "virtual reality", "augmented reality", "games", "video games", "board games",
    "cards", "toys", "playground", "park", "zoo", "aquarium", "carnival", "roller coaster", "ferris wheel", "balloon",
    "parachute", "skydiving", "bungee jumping", "rock climbing", "martial arts", "boxing", "wrestling", "tennis", "golf",
    "soccer", "football", "basketball", "baseball", "hockey", "racing", "horseback riding", "rodeo", "fishing", "hunting",
    "campfire", "tent", "cabin", "wilderness", "jungle", "safari", "desert", "canyon", "cliff", "cave", "mine", "fossil",
    "dinosaur", "history", "ancient", "medieval", "renaissance", "victorian", "modern", "future", "robot", "AI", "cyber",
    "cybersecurity", "network", "coding", "programming", "software", "hardware", "electronics", "gadgets", "wearables",
    "smartwatch", "drone", "satellite", "space station", "astronaut", "alien", "UFO", "extraterrestrial", "mystical", 
    "magical", "legendary", "mythology", "folklore", "fairy tale", "dragon", "unicorn", "mermaid", "witch", "wizard", 
    "vampire", "werewolf", "zombie", "monster", "ghost", "spirit", "angel", "demon", "religion", "church", "temple", 
    "mosque", "synagogue", "prayer", "meditation", "faith", "belief", "ritual", "ceremony", "wedding", "funeral", 
    "birth", "death", "rebirth", "reincarnation", "afterlife", "paradise", "hell", "heaven", "purgatory", "nirvana", 
    "enlightenment", "awakening", "consciousness", "mind", "brain", "thought", "idea", "creativity", "imagination", 
    "dream", "nightmare", "vision", "intuition", "perception", "sensation", "emotion", "feeling", "love", "hate", 
    "anger", "sadness", "happiness", "joy", "fear", "courage", "hope", "despair", "peace", "chaos", "balance", 
    "harmony", "discord", "conflict", "resolution", "solution", "problem", "challenge", "opportunity", "risk", "reward", 
    "success", "failure", "win", "lose", "competition", "cooperation", "teamwork", "leadership", "followership", 
    "mentor", "apprentice", "teacher", "student", "parent", "child", "sibling", "friend", "enemy", "ally", "opponent", 
    "partner", "lover", "spouse", "divorce", "breakup", "reunion", "beginning", "end", "past", "present", "future", 
    "history", "legacy", "heritage", "tradition", "innovation", "change", "stability", "revolution", "evolution", 
    "progress", "regression", "growth", "decay", "birth", "death", "renewal", "transformation", "transition", 
    "migration", "settlement", "exploration", "discovery", "adventure", "journey", "quest", "search", "research", 
    "study", "learn", "teach", "guide", "follow", "lead", "command", "obey", "rule", "serve", "govern", "rebel", 
    "comply", "resist", "accept", "reject", "approve", "disapprove", "praise", "criticize", "commend", "condemn", 
    "reward", "punish", "bless", "curse", "heal", "hurt", "help", "hinder", "protect", "attack", "defend", "offend", 
    "pride", "humility", "arrogance", "modesty", "confidence", "insecurity", "strength", "weakness", "ability", 
    "disability", "talent", "skill", "knowledge", "ignorance", "wisdom", "foolishness", "sense", "nonsense", 
    "meaning", "meaninglessness", "purpose", "pointlessness", "significance", "insignificance", "importance", 
    "triviality", "priority", "neglect", "attention", "distraction", "focus", "scatter", "clarity", "confusion", 
    "certainty", "doubt", "belief", "skepticism", "faith", "atheism", "religion", "secularism", "spirituality", 
    "materialism", "idealism", "realism", "optimism", "pessimism", "hope", "despair", "happiness", "sadness", "joy", 
    "sorrow", "pleasure", "pain", "comfort", "discomfort", "ease", "difficulty", "simplicity", "complexity", 
    "clarity", "ambiguity", "transparency", "opacity", "openness", "closure", "inclusion", "exclusion", "unity", 
    "division", "cohesion", "separation", "connection", "isolation", "association", "dissociation", "integration", 
    "disintegration", "combination", "fragmentation", "construction", "destruction", "creation", "annihilation", 
    "birth", "death", "life", "afterlife", "existence", "nonexistence", "reality", "illusion", "truth", "lie", 
    "honesty", "deception", "sincerity", "insincerity", "authenticity", "fakeness", "genuineness", "duplicity", 
    "integrity", "corruption", "morality", "immorality", "ethics", "unethical", "virtue", "vice", "good", "evil", 
    "right", "wrong", "justice", "injustice", "fairness", "unfairness", "equality", "inequality", "freedom", 
    "oppression", "liberty", "slavery", "autonomy", "dependency", "independence", "colonialism", "sovereignty", 
    "occupation", "dominance", "submission", "control", "chaos", "order", "disorder", "structure", "randomness", 
    "pattern", "anomaly", "norm", "deviation", "standard", "exception", "rule", "exception", "law", "anarchy", 
    "governance", "lawlessness", "authority", "rebellion", "power", "weakness", "strength", "vulnerability", 
    "resilience", "fragility", "stability", "instability", "consistency", "inconsistency", "predictability", 
    "unpredictability", "reliability", "unreliability", "trustworthiness", "untrustworthiness", "loyalty", "betrayal", 
    "allegiance", "treason", "fidelity", "infidelity", "commitment", "abandonment", "dedication", "apathy", "passion", 
    "indifference", "enthusiasm", "lackluster", "energy", "lethargy", "vigor", "fatigue", "vitality", "enervation", 
    "life", "death", "existence", "void", "being", "nothingness", "reality", "fantasy", "fact", "fiction", "history", 
    "myth", "truth", "lie", "evidence", "speculation", "certainty", "doubt", "clarity", "confusion", "understanding", 
    "misunderstanding", "knowledge", "ignorance", "wisdom", "foolishness", "insight", "blindness", "vision", "myopia", 
    "perspective", "bias", "objectivity", "subjectivity", "impartiality", "prejudice", "tolerance", "intolerance", 
    "acceptance", "rejection", "inclusion", "exclusion", "embracing", "repulsion", "attraction", "aversion", "affection", 
    "antipathy", "love", "hate", "compassion", "indifference", "empathy", "apathy", "kindness", "cruelty", "generosity", 
    "selfishness", "altruism", "egotism", "selflessness", "narcissism", "humility", "arrogance", "modesty", "vanity", 
    "pride", "shame", "honor", "dishonor", "respect", "disrespect", "admiration", "contempt", "esteem", "derision", 
    "value", "worthlessness", "importance", "insignificance", "significance", "triviality", "meaning", "meaninglessness", 
    "purpose", "purposelessness", "goal", "aimlessness", "intention", "unintention", "design", "accident", "plan", 
    "randomness", "strategy", "tactics", "method", "chaos", "approach", "avoidance", "pursuit", "escape", "chase", 
    "flee", "attack", "defense", "offense", "protection", "threat", "security", "danger", "safety", "risk", "certainty", 
    "uncertainty", "predictability", "unpredictability", "probability", "improbability", "likelihood", "unlikelihood", 
    "chance", "certainty", "fate", "freewill", "destiny", "choice", "predetermination", "freedom", "necessity", 
    "contingency", "inevitability", "possibility", "impossibility", "potential", "actuality", "capability", "incapability", 
    "capacity", "limitation", "ability", "disability", "talent", "incompetence", "skill", "awkwardness", "mastery", 
    "novice", "expertise", "ignorance", "knowledge", "learning", "education", "instruction", "ignorance", "wisdom", 
    "folly", "intelligence", "stupidity", "smartness", "dullness", "brightness", "dimness", "light", "darkness", "illumination", 
    "obfuscation", "clarity", "ambiguity", "transparency", "opacity", "visibility", "invisibility", "presence", "absence", 
    "existence", "nonexistence", "reality", "illusion", "actuality", "fantasy", "fact", "fiction", "truth", "lie", 
    "honesty", "deception", "authenticity", "fakeness", "genuineness", "duplicity", "sincerity", "insincerity", "realism", 
    "idealism", "pragmatism", "romanticism", "cynicism", "optimism", "pessimism", "hope", "despair", "faith", "doubt", 
    "belief", "skepticism", "trust", "mistrust", "confidence", "insecurity", "assurance", "uncertainty", "certainty", 
    "ambiguity", "ambivalence", "decisiveness", "indecision", "resolution", "inconclusiveness", "conclusion", "continuation", 
    "end", "beginning", "completion", "incompleteness", "whole", "part", "totality", "fragment", "unity", "division", 
    "singularity", "multiplicity", "oneness", "diversity", "individuality", "collectivity", "identity", "difference", 
    "sameness", "alterity", "self", "other", "ego", "alter ego", "persona", "shadow", "conscious", "unconscious", 
    "awareness", "ignorance", "insight", "blindness", "perception", "misconception", "vision", "illusion", "sight", 
    "invisibility", "audition", "deafness", "hearing", "silence", "speech", "muteness", "voice", "voicelessness", 
    "articulation", "inarticulateness", "expression", "repression", "assertion", "suppression", "affirmation", "negation", 
    "confirmation", "denial", "agreement", "disagreement", "consensus", "dissension", "harmony", "discord", "accord", 
    "conflict", "peace", "war", "truce", "hostility", "friendship", "enmity", "alliance", "rivalry", "cooperation", 
    "competition", "collaboration", "opposition", "support", "hindrance", "help", "obstacle", "advantage", "benefit", 
    "drawback", "gain", "loss", "profit", "deficit", "surplus", "shortage", "abundance", "scarcity", "plenty", "paucity", 
    "wealth", "poverty", "richness", "indigence", "affluence", "destitution", "prosperity", "adversity", "luck", "misfortune", 
    "fortune", "disaster", "chance", "fate", "randomness", "design", "accident", "intention", "coincidence", "purpose", 
    "plan", "chaos", "strategy", "tactics", "method", "approach", "avoidance", "pursuit", "retreat", "advance", "progress", 
    "regress", "development", "stagnation", "growth", "decay", "expansion", "contraction", "inflation", "deflation", 
    "boom", "bust", "rise", "fall", "ascension", "descent", "climbing", "sinking", "floating", "drowning", "swimming", 
    "submerging", "emergence", "immersion", "appearance", "disappearance", "visibility", "invisibility", "manifestation", 
    "concealment", "revelation", "mystery", "clarity", "obscurity", "transparency", "opacity", "brightness", "dimness", 
    "light", "darkness", "day", "night", "morning", "evening", "sunrise", "sunset", "dawn", "dusk", "noon", "midnight", 
    "spring", "autumn", "summer", "winter", "heat", "cold", "warmth", "chill", "temperature", "climate", "weather", 
    "atmosphere", "environment", "nature", "culture", "wilderness", "civilization", "rural", "urban", "countryside", 
    "city", "village", "metropolis", "town", "capital", "colony", "territory", "state", "nation", "country", "empire", 
    "kingdom", "republic", "democracy", "dictatorship", "monarchy", "oligarchy", "anarchy", "order", "chaos", "law", 
    "lawlessness", "justice", "injustice", "fairness", "unfairness", "equity", "inequity", "balance", "imbalance", 
    "symmetry", "asymmetry", "harmony", "discord", "music", "noise", "melody", "dissonance", "rhythm", "irregularity", 
    "beat", "offbeat", "tune", "atonality", "song", "silence", "sound", "quiet", "loudness", "softness", "pitch", 
    "flatness", "highness", "lowness", "tone", "note", "chord", "key", "scale", "mode", "major", "minor", "harmonic", 
    "melodic", "lyric", "narrative", "story", "tale", "account", "report", "description", "explanation", "elaboration", 
    "simplification", "complication", "clarification", "obfuscation", "illustration", "representation", "depiction", 
    "portrayal", "image", "picture", "photograph", "painting", "drawing", "sketch", "outline", "doodle", "design", 
    "pattern", "model", "example", "prototype", "archetype", "standard", "deviation", "norm", "anomaly", "rule", 
    "exception", "average", "extreme", "mean", "median", "mode", "variation", "uniformity", "diversity", "variety", 
    "sameness", "difference", "distinction", "similarity", "comparison", "contrast", "analogy", "dissimilarity", 
    "relation", "disconnection", "association", "dissociation", "connection", "separation", "link", "break", 
    "bond", "division", "union", "disunion", "marriage", "divorce", "engagement", "separation", "relationship", 
    "estrangement", "friendship", "enmity", "affection", "antipathy", "love", "hate", "passion", "indifference", 
    "enthusiasm", "apathy", "zeal", "lackluster", "vigor", "lethargy", "energy", "fatigue", "strength", "weakness", 
    "might", "impotence", "power", "powerlessness", "dominance", "submission", "control", "freedom", "restraint", 
    "liberation", "limitation", "unboundedness", "boundary", "border", "edge", "center", "periphery", "core", 
    "surface", "depth", "shallow", "deep", "high", "low", "above", "below", "over", "under", "top", "bottom", 
    "up", "down", "front", "back", "left", "right", "north", "south", "east", "west", "direction", "misdirection", 
    "guidance", "misguidance", "leadership", "followership", "command", "obedience", "order", "chaos", "structure", 
    "randomness", "organization", "disorganization", "arrangement", "disarrangement", "composition", "decomposition", 
    "formation", "dissolution", "creation", "destruction", "building", "demolition", "construction", "ruin", 
    "making", "breaking", "production", "consumption", "invention", "discovery", "innovation", "tradition", 
    "novelty", "custom", "change", "stability", "transformation", "preservation", "revolution", "continuity", 
    "progress", "regression", "advance", "retreat", "growth", "decay", "development", "underdevelopment", "evolution", 
    "devolution", "ascension", "descension", "rise", "fall", "climbing", "descending", "soaring", "sinking", 
    "floating", "drowning", "flying", "landing", "taking off", "touching down", "launching", "returning", "departure", 
    "arrival", "beginning", "end", "start", "finish", "opening", "closing", "commencement", "conclusion", "inauguration", 
    "termination", "birth", "death", "life", "afterlife", "existence", "nonexistence", "reality", "illusion", "fact", 
    "fiction", "truth", "lie", "honesty", "deception", "sincerity", "insincerity", "genuineness", "fakeness", "authenticity", 
    "duplicity", "reality", "fantasy", "actuality", "potentiality", "presence", "absence", "visibility", "invisibility", 
    "manifestation", "concealment", "appearance", "disappearance", "emergence", "submergence", "rise", "fall", "increase", 
    "decrease", "gain", "loss", "profit", "deficit", "advantage", "disadvantage", "benefit", "drawback", "pro", "con", 
    "plus", "minus", "positive", "negative", "affirmative", "negative", "yes", "no", "true", "false", "correct", "incorrect", 
    "right", "wrong", "accurate", "inaccurate", "precise", "imprecise", "exact", "vague", "clear", "ambiguous", "definite", 
    "indefinite", "determinate", "indeterminate", "fixed", "variable", "constant", "changing", "steady", "unsteady", 
    "stable", "unstable", "firm", "shaky", "solid", "liquid", "hard", "soft", "rigid", "flexible", "stiff", "loose", 
    "tight", "slack", "dense", "sparse", "thick", "thin", "broad", "narrow", "wide", "slim", "fat", "skinny", 
    "heavy", "light", "weighty", "weightless", "massive", "tiny", "large", "small", "gigantic", "minute", "colossal", 
    "microscopic", "huge", "petite", "enormous", "insignificant", "major", "minor", "important", "trivial", "significant", 
    "negligible", "noteworthy", "unnoticeable", "remarkable", "ordinary", "extraordinary", "common", "rare", "usual", 
    "unusual", "standard", "exceptional", "normal", "abnormal", "regular", "irregular", "typical", "atypical", "expected", 
    "unexpected", "predictable", "surprising", "routine", "novel", "habitual", "sporadic", "constant", "intermittent", 
    "chronic", "acute", "permanent", "temporary", "enduring", "transient", "lasting", "fleeting", "eternal", "momentary", 
    "timeless", "timed", "ancient", "modern", "old", "new", "vintage", "contemporary", "historic", "current", "past", 
    "present", "future", "yesterday", "today", "tomorrow", "now", "then", "before", "after", "previously", "subsequently", 
    "early", "late", "soon", "eventually", "immediately", "ultimately", "quickly", "slowly", "rapidly", "gradually", 
    "hastily", "deliberately", "suddenly", "progressively", "spontaneously", "premeditatedly", "intentionally", "accidentally", 
    "purposely", "inadvertently", "knowingly", "unknowingly", "consciously", "unconsciously", "voluntarily", "involuntarily", 
    "willingly", "reluctantly", "eagerly", "hesitantly", "readily", "grudgingly", "enthusiastically", "lukewarmly", "passionately", 
    "indifferently", "zealously", "apathetically", "fervently", "coolly", "hotly", "coldly", "warmly", "chillily", 
    "affectionately", "hostilely", "amicably", "antagonistically", "friendly", "unfriendly", "kind", "unkind", "loving", 
    "hateful", "caring", "neglectful", "considerate", "inconsiderate", "sympathetic", "unsympathetic", "empathetic", "unempathetic", 
    "compassionate", "heartless", "generous", "stingy", "charitable", "selfish", "altruistic", "greedy", "selfless", 
    "self-centered", "unselfish", "egocentric", "humble", "arrogant", "modest", "conceited", "shy", "outgoing", "introverted", 
    "extroverted", "reserved", "effusive", "reticent", "talkative", "silent", "loquacious", "laconic", "wordy", "terse", 
    "verbose", "succinct", "detailed", "brief", "comprehensive", "concise", "thorough", "sketchy", "meticulous", "careless", 
    "careful", "reckless", "cautious", "rash", "prudent", "imprudent", "wise", "foolish", "intelligent", "stupid", 
    "smart", "dumb", "bright", "dim", "quick", "slow", "fast", "leisurely", "hasty", "procrastinating", "urgent", 
    "unhurried", "immediate", "delayed", "prompt", "late", "timely", "untimely", "punctual", "tardy", "early", 
    "belated", "previous", "subsequent", "former", "latter", "first", "last", "initial", "final", "beginning", 
    "end", "start", "finish", "opening", "closing", "commencement", "termination", "onset", "conclusion", "inception", 
    "culmination", "birth", "death", "creation", "destruction", "genesis", "apocalypse", "origin", "destiny", "source", 
    "outcome", "cause", "effect", "reason", "result", "motive", "consequence", "purpose", "aftermath", "intention", 
    "repercussion", "plan", "reaction", "strategy", "response", "method", "feedback", "procedure", "evaluation", "process", 
    "assessment", "system", "judgment", "structure", "opinion", "framework", "belief", "format", "conviction", "scheme", 
    "doubt", "pattern", "skepticism", "routine", "certainty", "habit", "uncertainty", "practice", "ambiguity", "custom", 
    "ambivalence", "tradition", "neutrality", "convention", "indifference", "norm", "interest", "rule", "boredom", "law", 
    "enthusiasm", "principle", "apathy", "theory", "passion", "hypothesis", "dispassion", "thesis", "detachment", "argument", 
    "attachment", "proof", "independence", "evidence", "dependence", "demonstration", "reliance", "indication", "autonomy", 
    "sign", "submission", "symptom", "domination", "mark", "subjugation", "token", "freedom", "badge", "constraint", 
    "emblem", "restraint", "symbol", "compulsion", "representation", "coercion", "image", "force", "likeness", "violence", 
    "resemblance", "aggression", "similarity", "opposition", "analogy", "resistance", "comparison", "conflict", "equivalence", 
    "struggle", "parity", "battle", "equality", "war", "uniformity", "fight", "consistency", "combat", "conformity", 
    "assault", "standardization", "attack", "regulation", "defense", "rule", "protection", "law", "security", "order", 
    "safety", "command", "danger", "directive", "peril", "instruction", "threat", "advice", "menace", "guidance", 
    "hazard", "direction", "risk", "orientation", "jeopardy", "position", "harm", "location", "injury", "place", 
    "pain", "site", "suffering", "spot", "agony", "setting", "torment", "background", "anguish", "context", "torture", 
    "circumstance", "trauma", "situation", "tragedy", "condition", "disaster", "state", "catastrophe", "status", 
    "calamity"

]

print("number of keywords: ", len(keywords))